# This is a basic workflow to help you get started with Actions

name: Running testsuite

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
        - main
  
  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Run Testsuite 
    runs-on: windows-latest
    steps:
    - name: build
      run: |
       echo "bulding"
       sleep 10s
      -uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
         repo: testselenim
      github_token: ${{secrets.G_ACCESS_TOKEN}}
      workflow_file_name: master.yml
    # Runs a single command using the runners shell
      -name: Build test suite
        run: |
         echo "Running test suite"
          sleep 10s

     
